 * Author: Takuho Ri (Zehao Li)
 * Modified time: 2025-02-10 19:08:32
 * Description: AttentiveFP test notebooks

In [1]:
import sys
import os
import importlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from rdkit import Chem
from rdkit.Chem import AllChem
import torch
import torch_geometric

sys.path.append(os.getcwd().split("/experiments")[0])

from src.layers import FourierKAN_Layer, MLP_Layer
import src.utils as utils
import src.AttentiveFP.data_handler as dh 

In [2]:
# ライブラリリロード用
importlib.reload(dh)
importlib.reload(utils)

<module 'src.utils' from '/workspace/ToxPred/MolKAN/molkan/src/utils.py'>

In [3]:
df = pd.read_csv("/workspace/ToxPred/MolKAN/molkan/data/tox_csv/bace.csv", index_col=0)
smiles = np.array(df["cano_smi"])
y = np.array(df[["Class"]])
print(smiles)
print(y)

['Cc1ccccc1-c1ccc2nc(N)c(C[C@@H](C)C(=O)N[C@@H]3CCOC(C)(C)C3)cc2c1'
 'CCCO[C@H]1C[NH2+][C@@H]([C@@H](O)[C@H](Cc2cc(F)cc(F)c2)NC(=O)[C@H](CCc2ccccc2)N2CC[C@@](CC(C)C)(NC(C)=O)C2=O)C1'
 'CCc1cn2c3c(cc(C(=O)N[C@@H](Cc4ccccc4)[C@H](O)C[NH2+]Cc4cccc(OC)c4)cc13)N(C)S(=O)(=O)CC2'
 ... 'Cn1c(N)nc(C2CC2c2cccc(Br)c2)cc1=O'
 'Cn1c(N)nc(C2CC2c2cccc(-c3ccccc3)c2)cc1=O'
 'Nc1nc2cc(Cl)ccc2n1CCCC(=O)NCC1CC1']
[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


In [4]:
print(np.array(smiles[[0, 1]]))
print(type(np.array(smiles[[0, 1]])))

['Cc1ccccc1-c1ccc2nc(N)c(C[C@@H](C)C(=O)N[C@@H]3CCOC(C)(C)C3)cc2c1'
 'CCCO[C@H]1C[NH2+][C@@H]([C@@H](O)[C@H](Cc2cc(F)cc(F)c2)NC(=O)[C@H](CCc2ccccc2)N2CC[C@@](CC(C)C)(NC(C)=O)C2=O)C1']
<class 'numpy.ndarray'>


In [5]:
datasets = dh.AttentiveFPDatasets(smiles, y)

In [6]:
datasets.labels

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [7]:
import torch.utils
import torch.utils.data


test = torch.utils.data.Subset(datasets, [0, 1, 2])

In [13]:
test.use_chirarity

AttributeError: 'Subset' object has no attribute 'use_chirarity'

In [16]:
a = torch.tensor([1])

In [17]:
print(a)

tensor([1])


In [27]:
utils.fix_seed(42)

In [5]:
utils.fix_seed(42)
from torch.utils.data import Dataset, DataLoader

a = torch.rand([100, 5])
b = torch.rand([100])

class simpledataset(Dataset):
    def __init__(self, a, b):
        super().__init__()
        self.a = a
        self.b = b
    def __len__(self):
        return len(a)
    def __getitem__(self, index):
        return self.a[index], self.b[index]

d = simpledataset(a, b)
l = DataLoader(d, batch_size=8, shuffle=True, num_workers=8, pin_memory=True)

c = 0

for a2, b2 in l:
    print(a2)
    print(b2)
    print(a2.shape)
    print(b2.shape)
    break

tensor([[0.8572, 0.1165, 0.8596, 0.2636, 0.6855],
        [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
        [0.9477, 0.7935, 0.8777, 0.4331, 0.2249],
        [0.9559, 0.7885, 0.2089, 0.4351, 0.1314],
        [0.2814, 0.7886, 0.5895, 0.7539, 0.1952],
        [0.7498, 0.2409, 0.1626, 0.3403, 0.6049],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.5811, 0.4129, 0.0369, 0.3179, 0.6273]])
tensor([0.3636, 0.7296, 0.2502, 0.9170, 0.4078, 0.1045, 0.2584, 0.6360])
torch.Size([8, 5])
torch.Size([8])
